---
title: "Figure 1"
output: html_notebook
---

# load libraries
```{r}
library(readr)
library(ggplot2)
library(gridExtra)
library(cluster)
library(forcats)
```

# Load data

```{r}
arabic <- read_csv("arabic_defining.csv")
english <- read_csv("english_defining.csv")
farsi <- read_csv("farsi_defining.csv")
french <- read_csv("french_defining.csv")
german <- read_csv("german_defining.csv")
spanish <- read_csv("spanish_defining.csv")
urdu <- read_csv("urdu_defining.csv")
wolof <- read_csv("wolof_defining.csv")
chinese <- read_csv("chinese_defining_pca0.csv")
```
# Chinese
```{r}
#Re-order data by words
chinese$words <- fct_inorder(chinese$words)

p_Chinese <- ggplot(data = chinese, aes(x = ordered(words), y = gender_bias, fill = pos)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(title = "Chinese",
       y = "Gender Bias",
       x = element_blank()) +
  scale_fill_manual(values = c( "dodgerblue2", "firebrick2")) +
  expand_limits(y = c(-0.8,0.8))
p_Chinese <- p_Chinese + theme(
  legend.position = "none",
  text = element_text(family = "Gill Sans"),
  plot.title = element_text(hjust = 0.5)
) 
p_Chinese

```

# Arabic
```{r}
#Re-order data by words
arabic$words <- fct_inorder(arabic$words)

p_Arabic <- ggplot(data = arabic, aes(x = ordered(words), y = gender_bias, fill = pos)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(title = "Arabic",
       y = "Gender Bias",
       x = element_blank()) +
  scale_fill_manual(values = c( "dodgerblue2", "firebrick2")) +
  expand_limits(y = c(-0.8,0.8))
p_Arabic <- p_Arabic + theme(
  legend.position = "none",
  text = element_text(family = "Gill Sans"),
  plot.title = element_text(hjust = 0.5)
) 
p_Arabic

```

# English
```{r}

#Re-order by defining set
english$words <- fct_inorder(english$words)

p_English <- ggplot(data = english, aes(x = ordered(words), y = gender_bias, fill = pos)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(title = "English",
       y = "Gender Bias",
       x = element_blank()) +
  scale_fill_manual(values = c( "dodgerblue2", "firebrick2")) +
expand_limits(y = c(-0.8,0.8))
p_English <- p_English + theme(
  legend.position = "none",
  text = element_text(family = "Gill Sans"),
  plot.title = element_text(hjust = 0.5)
) 
p_English
```

# Farsi

```{r}
farsi$words <- fct_inorder(farsi$words)

p_Farsi <- ggplot(data = farsi, aes(x = ordered(words), y = gender_bias, fill = pos)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(title = "Farsi",
       y = "Gender Bias",
       x = element_blank()) +
  scale_fill_manual(values = c( "dodgerblue2", "firebrick2")) +
  expand_limits(y = c(-0.8,0.8))
p_Farsi <- p_Farsi + theme(
  legend.position = "none",
  text = element_text(family = "Gill Sans"),
  plot.title = element_text(hjust = 0.5)
) 
p_Farsi


```

# French

```{r}

french$words <- fct_inorder(french$words)
p_French <- ggplot(data = french, aes(x = ordered(words), y = gender_bias, fill = pos)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(title = "French",
       y = "Gender Bias",
       x = element_blank()) +
  scale_fill_manual(values = c( "dodgerblue2", "firebrick2")) +
 expand_limits(y = c(-0.8,0.8))
p_French  <-p_French  + theme(
  legend.position = "none",
  text = element_text(family = "Gill Sans"),
  plot.title = element_text(hjust = 0.5)
) 
p_French 
```

# German
```{r}
german$words <- fct_inorder(german$words)

p_German <- ggplot(data = german, aes(x = ordered(words), y = gender_bias, fill = pos)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(title = "German",
       y = "Gender Bias",
       x = element_blank()) +
  scale_fill_manual(values = c( "dodgerblue2", "firebrick2")) +
  expand_limits(y = c(-0.8,0.8))
p_German <- p_German + theme(
  legend.position = "none",
  text = element_text(family = "Gill Sans"),
  plot.title = element_text(hjust = 0.5)
) 
p_German

```

#Spanish
```{r}
spanish$words <- fct_inorder(spanish$words)

p_Spanish <- ggplot(data = spanish, aes(x = ordered(words), y = gender_bias, fill = pos)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(title = "Spanish",
       y = "Gender Bias",
       x = element_blank()) +
  scale_fill_manual(values = c( "dodgerblue2", "firebrick2")) +
expand_limits(y = c(-0.8,0.8))
p_Spanish  <- p_Spanish  + theme(
  legend.position = "none",
  text = element_text(family = "Gill Sans"),
  plot.title = element_text(hjust = 0.5)
) 
p_Spanish 
```

# Urdu 
```{r}
urdu$words <- fct_inorder(urdu$words)

p_Urdu <- ggplot(data = urdu, aes(x = ordered(words), y = gender_bias, fill = pos)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(title = "Urdu",
       y = "Gender Bias",
       x = element_blank()) +
  scale_fill_manual(values = c( "dodgerblue2", "firebrick2")) +
expand_limits(y = c(-0.8,0.8))
p_Urdu  <- p_Urdu  + theme(
  legend.position = "none",
  text = element_text(family = "Gill Sans"),
  plot.title = element_text(hjust = 0.5)
) 
p_Urdu 


```

# Wolof
```{r}
wolof$words <- fct_inorder(wolof$words)

p_Wolof <- ggplot(data = wolof, aes(x = ordered(words), y = gender_bias, fill = pos)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(title = "Wolof",
       y = "Gender Bias",
       x = element_blank()) +
  scale_fill_manual(values = c( "firebrick2", "dodgerblue2")) +
expand_limits(y = c(-0.8,0.8))
p_Wolof  <- p_Wolof  + theme(
  legend.position = "none",
  text = element_text(family = "Gill Sans"),
  plot.title = element_text(hjust = 0.5)
) 
p_Wolof 


```

# Arrange plot objects into a grid
```{r}

p_total <- grid.arrange(p_Chinese, p_English, p_Spanish, p_Arabic, p_German, p_French, p_Farsi, p_Urdu, p_Wolof, nrow = 3)
p_total
```
```{r}
ggsave(file = "DefiningSet_pairsTogether.png", arrangeGrob(p_Chinese, p_English, p_Spanish, p_Arabic, p_German, p_French, p_Farsi, p_Urdu, p_Wolof, ncol = 3))

```

# Chinese By Gender
```{r}
#Re-order data by words
chinese$expected_gender <- fct_inorder(chinese$expected_gender)

p_ChineseGenderSummary <- ggplot(data = chinese, aes(x = ordered(expected_gender), y = gender_bias, fill = pos)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(title = "Chinese ",
       y = "Gender Bias",
       x = element_blank()) +
  scale_fill_manual(values = c( "dodgerblue2", "firebrick2")) +
  expand_limits(y = c(-0.8,0.8))
p_ChineseGenderSummary <- p_ChineseGenderSummary + theme(
  legend.position = "none",
  text = element_text(family = "Gill Sans"),
  plot.title = element_text(hjust = 0.5)
) 
p_ChineseGenderSummary

```

# Arabic
```{r}
#Re-order data by words
arabic$expected_gender <- fct_inorder(arabic$expected_gender)

p_ArabicGenderSummary <- ggplot(data = arabic, aes(x = ordered(expected_gender), y = gender_bias, fill = pos)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(title = "Arabic",
       y = "Gender Bias",
       x = element_blank()) +
  scale_fill_manual(values = c( "dodgerblue2", "firebrick2")) +
  expand_limits(y = c(-0.8,0.8))
p_ArabicGenderSummary <- p_ArabicGenderSummary + theme(
  legend.position = "none",
  text = element_text(family = "Gill Sans"),
  plot.title = element_text(hjust = 0.5)
) 
p_ArabicGenderSummary

```

# English
```{r}

#Re-order by defining set
english$expected_gender <- fct_inorder(english$expected_gender)

p_EnglishGenderSummary <- ggplot(data = english, aes(x = ordered(expected_gender), y = gender_bias, fill = pos)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(title = "English",
       y = "Gender Bias",
       x = element_blank()) +
  scale_fill_manual(values = c( "dodgerblue2", "firebrick2")) +
expand_limits(y = c(-0.8,0.8))
p_EnglishGenderSummary <-p_EnglishGenderSummary + theme(
  legend.position = "none",
  text = element_text(family = "Gill Sans"),
  plot.title = element_text(hjust = 0.5)
) 
p_EnglishGenderSummary
```

# Farsi

```{r}
farsi$expected_gender <- fct_inorder(farsi$expected_gender)

p_FarsiGenderSummary <- ggplot(data = farsi, aes(x = ordered(expected_gender), y = gender_bias, fill = pos)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(title = "Farsi",
       y = "Gender Bias",
       x = element_blank()) +
  scale_fill_manual(values = c( "dodgerblue2", "firebrick2")) +
  expand_limits(y = c(-0.8,0.8))
p_FarsiGenderSummary <- p_FarsiGenderSummary + theme(
  legend.position = "none",
  text = element_text(family = "Gill Sans"),
  plot.title = element_text(hjust = 0.5)
) 
p_FarsiGenderSummary


```

# French

```{r}

french$expected_gender <- fct_inorder(french$expected_gender)
p_FrenchGenderSummmary <- ggplot(data = french, aes(x = ordered(expected_gender), y = gender_bias, fill = pos)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(title = "French",
       y = "Gender Bias",
       x = element_blank()) +
  scale_fill_manual(values = c( "dodgerblue2", "firebrick2")) +
 expand_limits(y = c(-0.8,0.8))
p_FrenchGenderSummmary <- p_FrenchGenderSummmary + theme(
  legend.position = "none",
  text = element_text(family = "Gill Sans"),
  plot.title = element_text(hjust = 0.5)
) 
p_FrenchGenderSummmary
```

# German
```{r}
german$expected_gender <- fct_inorder(german$expected_gender)

p_GermanGenderSummmary <- ggplot(data = german, aes(x = ordered(expected_gender), y = gender_bias, fill = pos)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(title = "German",
       y = "Gender Bias",
       x = element_blank()) +
  scale_fill_manual(values = c( "dodgerblue2", "firebrick2")) +
  expand_limits(y = c(-0.8,0.8))
p_GermanGenderSummmary <- p_GermanGenderSummmary + theme(
  legend.position = "none",
  text = element_text(family = "Gill Sans"),
  plot.title = element_text(hjust = 0.5)
) 
p_GermanGenderSummmary

```

#Spanish
```{r}
spanish$expected_gender <- fct_inorder(spanish$expected_gender)

p_SpanishGenderSummmary <- ggplot(data = spanish, aes(x = ordered(expected_gender), y = gender_bias, fill = pos)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(title = "Spanish",
       y = "Gender Bias",
       x = element_blank()) +
  scale_fill_manual(values = c( "dodgerblue2", "firebrick2")) +
expand_limits(y = c(-0.8,0.8))
p_SpanishGenderSummmary <- p_SpanishGenderSummmary + theme(
  legend.position = "none",
  text = element_text(family = "Gill Sans"),
  plot.title = element_text(hjust = 0.5)
) 
p_SpanishGenderSummmary
```

# Urdu 
```{r}
urdu$expected_gender <- fct_inorder(urdu$expected_gender)

p_UrduGenderSummmary <- ggplot(data = urdu, aes(x = ordered(expected_gender), y = gender_bias, fill = pos)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(title = "Urdu",
       y = "Gender Bias",
       x = element_blank()) +
  scale_fill_manual(values = c( "dodgerblue2", "firebrick2")) +
expand_limits(y = c(-0.8,0.8))
p_UrduGenderSummmary <- p_UrduGenderSummmary + theme(
  legend.position = "none",
  text = element_text(family = "Gill Sans"),
  plot.title = element_text(hjust = 0.5)
) 
p_UrduGenderSummmary


```

# Wolof
```{r}
wolof$expected_gender <- fct_inorder(wolof$expected_gender)

p_WolofGenderSummmary <- ggplot(data = wolof, aes(x = ordered(expected_gender), y = gender_bias, fill = pos)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(title = "Wolof",
       y = "Gender Bias",
       x = element_blank()) +
  scale_fill_manual(values = c( "firebrick2", "dodgerblue2")) +
expand_limits(y = c(-0.8,0.8))
p_WolofGenderSummmary <- p_WolofGenderSummmary + theme(
  legend.position = "none",
  text = element_text(family = "Gill Sans"),
  plot.title = element_text(hjust = 0.5)
) 
p_WolofGenderSummmary


```

# Arrange plot objects into a grid
```{r}

p_DefiningSetGenderSummary <- grid.arrange(p_ChineseGenderSummary, p_SpanishGenderSummmary, p_EnglishGenderSummary, p_ArabicGenderSummary, p_GermanGenderSummmary, p_FrenchGenderSummmary, p_FarsiGenderSummary, p_UrduGenderSummmary, p_WolofGenderSummmary, nrow = 3)
p_DefiningSetGenderSummary
```
```{r}
ggsave(file = "DefiningSet_GenderSummary.png", arrangeGrob(p_ChineseGenderSummary, p_SpanishGenderSummmary, p_EnglishGenderSummary, p_ArabicGenderSummary, p_GermanGenderSummmary, p_FrenchGenderSummmary, p_FarsiGenderSummary, p_UrduGenderSummmary, p_WolofGenderSummmary, ncol = 3))
```
